#!/opt/homebrew/Cellar/ykman/5.7.2/libexec/bin/python
# -*- coding: utf-8 -*-
import re
import sys
from ykman._cli.__main__ import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
