name: Build and Release

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Determine version name
        id: version
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          else
            echo "VERSION=nightly" >> $GITHUB_ENV
          fi

      - name: Zip the mozilla folder
        run: |
          zip -r yubipass-mozilla-${{ env.VERSION }}.zip mozilla/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: yubipass-mozilla-${{ env.VERSION }}
          path: yubipass-mozilla-${{ env.VERSION }}.zip

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/') # Only create a release for tagged commits
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: yubipass-mozilla-${{ github.ref_name }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: yubipass-mozilla-${{ github.ref_name }}.zip
          token: ${{ secrets.GITHUB_TOKEN }}
