name: Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Zip the mozilla folder
        run: |
          zip -r yubipass-mozilla.zip mozilla/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: yubipass-mozilla
          path: yubipass-mozilla.zip

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: yubipass-mozilla

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: yubipass-mozilla.zip
          token: ${{ secrets.GITHUB_TOKEN }}
