name: Run Command and Zip Output

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Mozilla Extension
        run: |
          mkdir output
          zip -r output/yubi_pass.xpi mozilla/*

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: output-zip
          path: output.zip

      - name: Create Release
        id: create_release
        uses: actions/create-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.0
          release_name: Release v1.0.0
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: output.zip
          asset_name: output.zip
          asset_content_type: application/zip
